#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

rm -r /var/lock/*
/bin/usbh_power 1 1

/usr/sbin/inetd &
/usr/sbin/httpd -h /mnt/www/html &
/usr/sbin/telnetd -l /bin/sh
#/usr/bin/madplay -q /etc/start.mp3 &
echo "Welcome to SK-MAT91SAM9G45 development board!" > /dev/tty1
echo "www.starterkit.ru" > /dev/tty1

# add next string for turn off screensave
echo -e '\33[9;0]\33[14;0]' > /dev/tty1

#rm /initrd.image

mknod /dev/simcom_pwr c 135 0
