#!/bin/sh
#
# Start the system
#

    /bin/mount -t proc proc /proc
    /bin/mount -t sysfs sysfs /sys

    /bin/mount -t tmpfs mdev /dev
    /bin/mkdir /dev/pts
    /bin/mount -t devpts devpts /dev/pts

    /bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
    /sbin/mdev -s

#    /bin/mount -a
    
#    /usr/sbin/ubiattach /dev/ubi_ctrl -m 1
#    /bin/mount -t ubifs ubi0:nandfs /mnt/nand

#    /sbin/modprobe ehci_hcd
    